"""organization constraints

Revision ID: 13903769f767
Revises: e4c2f658c20a
Create Date: 2026-07-06 03:53:16.854963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13903769f767'
down_revision: Union[str, Sequence[str], None] = 'e4c2f658c20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_unique_constraint(None, 'organizations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.alter_column('organizations', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
